#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Godough.Generators.DI;

using Microsoft.CodeAnalysis;

[Generator]
public class DiSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Find all class declarations with [Serializable]
        var classDeclarations = context
            .SyntaxProvider.CreateSyntaxProvider(
                static (s, _) => IsCandidate(s), // quick filter
                static (ctx, _) => GetSemanticTarget(ctx)
            ) // get symbol
            .Where(static m => m is not null)!;

        // Step 2: Generate code for each matched class
        context.RegisterSourceOutput(
            classDeclarations,
            static (spc, classSymbol) =>
            {
                GenerateSerializer(spc, classSymbol!);
            }
        );
    }

    private static bool IsCandidate(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax;
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            return null;

        return symbol
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Any(p => p.GetAttributes().Any(a =>
                a.AttributeClass!.Name == "FromOwner"
                || a.AttributeClass.Name == "FromRoot"
                || a.AttributeClass.Name == "FromAutoload"
            ))
            ? symbol
            : null;
    }

    private static void GenerateSerializer(
        SourceProductionContext context,
        INamedTypeSymbol classSymbol
    )
    {
        var ns = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;

        var propsRoot = classSymbol
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetAttributes().Any(a => a.AttributeClass!.Name == "FromRoot"))
            .ToList();
        var propsOwner = classSymbol
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetAttributes().Any(a => a.AttributeClass!.Name == "FromOwner"))
            .ToList();
        var propsAutoload = classSymbol
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.GetAttributes().Any(a => a.AttributeClass!.Name == "FromAutoload"))
            .ToList();


        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//{DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("using Godough.Addons.NodeSelection;");
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"  public partial class {className}");
        sb.AppendLine("  {");

        GenerateFromRoot(propsRoot, sb);
        GenerateFromOwner(propsOwner, sb);
        GenerateFromAutoload(propsAutoload, sb);

        sb.AppendLine("  }");
        sb.AppendLine("}");

        context.AddSource($"{className}.di.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateFromAutoload(List<IPropertySymbol> propsRoot, StringBuilder sb)
    {
        foreach (var prop in propsRoot)
        {
            sb.AppendLine(
                $"    {SyntaxFacts.GetText(prop.DeclaredAccessibility)} partial {prop.Type} {prop.Name}"
            );
            sb.AppendLine($"    {{");
            sb.AppendLine($"      get => field ??= this.FindAutoload<{prop.Type}>(\"{prop.Type}\");");
            sb.AppendLine($"    }}");
        }
    }

    private static void GenerateFromRoot(List<IPropertySymbol> propsRoot, StringBuilder sb)
    {
        foreach (var prop in propsRoot)
        {
            sb.AppendLine(
                $"    {SyntaxFacts.GetText(prop.DeclaredAccessibility)} partial {prop.Type} {prop.Name}"
            );
            sb.AppendLine($"    {{");
            var argName = prop.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass!.Name == "FromRoot")!
                .NamedArguments;
            string? argNameValue = null;
            if (!argName.IsDefaultOrEmpty)
            {
                argNameValue = $"\"{argName.First().Value.Value}\"";
            }

            sb.AppendLine($"      get => field ??= this.FindUnderRoot<{prop.Type}>({argNameValue});");
            sb.AppendLine($"    }}");
        }
    }

    private static void GenerateFromOwner(List<IPropertySymbol> propsOwner, StringBuilder sb)
    {
        foreach (var prop in propsOwner)
        {
            sb.AppendLine(
                $"    {SyntaxFacts.GetText(prop.DeclaredAccessibility)} partial {prop.Type} {prop.Name}"
            );
            sb.AppendLine($"    {{");
            var argName = prop.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass!.Name == "FromOwner")!
                .NamedArguments;
            string? argNameValue = null;
            if (!argName.IsDefaultOrEmpty)
            {
                argNameValue = $"\"{argName.First().Value.Value}\"";
            }

            sb.AppendLine($"      get => field ??= this.FindUnder<{prop.Type}>({argNameValue});");

            sb.AppendLine($"    }}");
        }
    }
}
